### ISSUE TITLE
relocation R_X86_64_32S against `.rodata' can not be used when making a PIE object; recompile with -fPIC

### ISSUE THREAD

**Issue by darksylinc** [tpoechtrager/ldid#3]
I'm getting this error while trying to compile on my system.

This error can easily be fixed by appending -fPIC to FLAGS in the Makefile
I'm using:
gcc version 7.3.0 (Ubuntu 7.3.0-16ubuntu3) 
Xubuntu 18.04

**Comment by tpoechtrager** [comment]
Please file a pull request.
